//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaravelLauncher.Ressources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings_fr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings_fr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LaravelLauncher.Resources.Strings.fr", typeof(Strings_fr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processus actifs.
        /// </summary>
        internal static string ActiveProcesses {
            get {
                return ResourceManager.GetString("ActiveProcesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lancer npm.
        /// </summary>
        internal static string LaunchNpm {
            get {
                return ResourceManager.GetString("LaunchNpm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options de lancement.
        /// </summary>
        internal static string LaunchOptions {
            get {
                return ResourceManager.GetString("LaunchOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lancer le projet.
        /// </summary>
        internal static string LaunchProject {
            get {
                return ResourceManager.GetString("LaunchProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lancer yarn.
        /// </summary>
        internal static string LaunchYarn {
            get {
                return ResourceManager.GetString("LaunchYarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemin de l&apos;environnement de développement.
        /// </summary>
        internal static string LocalServerPath {
            get {
                return ResourceManager.GetString("LocalServerPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemin du projet.
        /// </summary>
        internal static string ProjectPath {
            get {
                return ResourceManager.GetString("ProjectPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titre du projet.
        /// </summary>
        internal static string ProjectTitle {
            get {
                return ResourceManager.GetString("ProjectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionner un dossier.
        /// </summary>
        internal static string SelectFolder {
            get {
                return ResourceManager.GetString("SelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Démarrer l&apos;environnement de développement.
        /// </summary>
        internal static string StartDevEnv {
            get {
                return ResourceManager.GetString("StartDevEnv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Démarrer les tâches planifiées.
        /// </summary>
        internal static string StartScheduledTasks {
            get {
                return ResourceManager.GetString("StartScheduledTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrêter l&apos;environnement de développement.
        /// </summary>
        internal static string StopDevEnv {
            get {
                return ResourceManager.GetString("StopDevEnv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fermer.
        /// </summary>
        internal static string TrayMenuExit {
            get {
                return ResourceManager.GetString("TrayMenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redémarrer tous les processus.
        /// </summary>
        internal static string TrayMenuRestartAllProcesses {
            get {
                return ResourceManager.GetString("TrayMenuRestartAllProcesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redémarrer l&apos;environnement de développement.
        /// </summary>
        internal static string TrayMenuRestartDevEnv {
            get {
                return ResourceManager.GetString("TrayMenuRestartDevEnv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redémarrer npm.
        /// </summary>
        internal static string TrayMenuRestartNpm {
            get {
                return ResourceManager.GetString("TrayMenuRestartNpm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redémarrer les tâches.
        /// </summary>
        internal static string TrayMenuRestartTasks {
            get {
                return ResourceManager.GetString("TrayMenuRestartTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redémarrer yarn.
        /// </summary>
        internal static string TrayMenuRestartYarn {
            get {
                return ResourceManager.GetString("TrayMenuRestartYarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agrandir.
        /// </summary>
        internal static string TrayMenuRestore {
            get {
                return ResourceManager.GetString("TrayMenuRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrêter tous les processus.
        /// </summary>
        internal static string TrayMenuStopAllProcesses {
            get {
                return ResourceManager.GetString("TrayMenuStopAllProcesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrêter l&apos;environnement de développement.
        /// </summary>
        internal static string TrayMenuStopDevEnv {
            get {
                return ResourceManager.GetString("TrayMenuStopDevEnv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrêter npm.
        /// </summary>
        internal static string TrayMenuStopNpm {
            get {
                return ResourceManager.GetString("TrayMenuStopNpm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrêter les tâches.
        /// </summary>
        internal static string TrayMenuStopTasks {
            get {
                return ResourceManager.GetString("TrayMenuStopTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arrêter yarn.
        /// </summary>
        internal static string TrayMenuStopYarn {
            get {
                return ResourceManager.GetString("TrayMenuStopYarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environnement de développement non défini.
        /// </summary>
        internal static string UnsetLocalServerPath {
            get {
                return ResourceManager.GetString("UnsetLocalServerPath", resourceCulture);
            }
        }
    }
}
