//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LaravelLauncher.Ressources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LaravelLauncher.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active processes.
        /// </summary>
        internal static string ActiveProcesses {
            get {
                return ResourceManager.GetString("ActiveProcesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start npm.
        /// </summary>
        internal static string LaunchNpm {
            get {
                return ResourceManager.GetString("LaunchNpm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start options.
        /// </summary>
        internal static string LaunchOptions {
            get {
                return ResourceManager.GetString("LaunchOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serve project.
        /// </summary>
        internal static string LaunchProject {
            get {
                return ResourceManager.GetString("LaunchProject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start yarn.
        /// </summary>
        internal static string LaunchYarn {
            get {
                return ResourceManager.GetString("LaunchYarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development environment path.
        /// </summary>
        internal static string LocalServerPath {
            get {
                return ResourceManager.GetString("LocalServerPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project path.
        /// </summary>
        internal static string ProjectPath {
            get {
                return ResourceManager.GetString("ProjectPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project title.
        /// </summary>
        internal static string ProjectTitle {
            get {
                return ResourceManager.GetString("ProjectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select folder.
        /// </summary>
        internal static string SelectFolder {
            get {
                return ResourceManager.GetString("SelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start development environment.
        /// </summary>
        internal static string StartDevEnv {
            get {
                return ResourceManager.GetString("StartDevEnv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run scheduled tasks.
        /// </summary>
        internal static string StartScheduledTasks {
            get {
                return ResourceManager.GetString("StartScheduledTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop development environment.
        /// </summary>
        internal static string StopDevEnv {
            get {
                return ResourceManager.GetString("StopDevEnv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string TrayMenuExit {
            get {
                return ResourceManager.GetString("TrayMenuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart All Processes.
        /// </summary>
        internal static string TrayMenuRestartAllProcesses {
            get {
                return ResourceManager.GetString("TrayMenuRestartAllProcesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart development environment.
        /// </summary>
        internal static string TrayMenuRestartDevEnv {
            get {
                return ResourceManager.GetString("TrayMenuRestartDevEnv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart npm.
        /// </summary>
        internal static string TrayMenuRestartNpm {
            get {
                return ResourceManager.GetString("TrayMenuRestartNpm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Tasks.
        /// </summary>
        internal static string TrayMenuRestartTasks {
            get {
                return ResourceManager.GetString("TrayMenuRestartTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart yarn.
        /// </summary>
        internal static string TrayMenuRestartYarn {
            get {
                return ResourceManager.GetString("TrayMenuRestartYarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        internal static string TrayMenuRestore {
            get {
                return ResourceManager.GetString("TrayMenuRestore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop All Processes.
        /// </summary>
        internal static string TrayMenuStopAllProcesses {
            get {
                return ResourceManager.GetString("TrayMenuStopAllProcesses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop development environment.
        /// </summary>
        internal static string TrayMenuStopDevEnv {
            get {
                return ResourceManager.GetString("TrayMenuStopDevEnv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop npm.
        /// </summary>
        internal static string TrayMenuStopNpm {
            get {
                return ResourceManager.GetString("TrayMenuStopNpm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Tasks.
        /// </summary>
        internal static string TrayMenuStopTasks {
            get {
                return ResourceManager.GetString("TrayMenuStopTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop yarn.
        /// </summary>
        internal static string TrayMenuStopYarn {
            get {
                return ResourceManager.GetString("TrayMenuStopYarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development evnironement is not set.
        /// </summary>
        internal static string UnsetLocalServerPath {
            get {
                return ResourceManager.GetString("UnsetLocalServerPath", resourceCulture);
            }
        }
    }
}
